[package]
name = "win32-module-table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
win32 = { path = "../win32" }
core-str = { path = "../core-str" }
