[package]
name = "win32-time"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core-time = { path = "../core-time" }

win32 = { path = "../win32" }