include_namespaces:
  - Windows.Win32.Foundation
  - Windows.Win32.Globalization
  - Windows.Win32.Graphics.DirectDraw
  - Windows.Win32.Graphics.Gdi
  - Windows.Win32.Security
  - Windows.Win32.Storage.FileSystem
  - Windows.Win32.System.Console
  - Windows.Win32.System.Diagnostics.Debug
  - Windows.Win32.System.Environment
  - Windows.Win32.System.IO
  - Windows.Win32.System.Kernel
  - Windows.Win32.System.LibraryLoader
  - Windows.Win32.System.Memory
  - Windows.Win32.System.SystemInformation
  - Windows.Win32.System.SystemServices
  - Windows.Win32.System.Threading
  - Windows.Win32.System.Time
  - Windows.Win32.System.WindowsProgramming
  - Windows.Win32.UI.WindowsAndMessaging

exclude_items:
  Windows.Win32.Foundation:
    - RtlNtStatusToDosError
    - SetLastErrorEx
    - SysAddRefString
    - SysAllocString
    - SysAllocStringByteLen
    - SysAllocStringLen
    - SysFreeString
    - SysReAllocString
    - SysReAllocStringLen
    - SysReleaseString
    - SysStringByteLen
    - SysStringLen
  Windows.Win32.System.Diagnostics.Debug:
    - PDEBUG_EXTENSION_CALL
    - PDEBUG_EXTENSION_KNOWN_STRUCT_EX
    - PDEBUG_EXTENSION_PROVIDE_VALUE
    - PDEBUG_EXTENSION_QUERY_VALUE_NAMES
    - TEXT_DOCUMENT_ARRAY
    - PROFILER_HEAP_OBJECT_RELATIONSHIP
    - PROFILER_HEAP_OBJECT_RELATIONSHIP_LIST
    - PROFILER_HEAP_OBJECT_OPTIONAL_INFO
    - WHEA_PCI_SLOT_NUMBER
    - WHEA_AER_ROOTPORT_DESCRIPTOR
    - AER_ROOTPORT_DESCRIPTOR_FLAGS
    - WHEA_AER_ENDPOINT_DESCRIPTOR
    - AER_ENDPOINT_DESCRIPTOR_FLAGS
    - WHEA_AER_BRIDGE_DESCRIPTOR
    - AER_BRIDGE_DESCRIPTOR_FLAGS
    - WHEA_DEVICE_DRIVER_DESCRIPTOR
    - WHEA_DRIVER_BUFFER_SET
    - WHEA_ERROR_SOURCE_CONFIGURATION_DD
    - WHEA_ERROR_SOURCE_CONFIGURATION_DEVICE_DRIVER
    - WHEA_ERROR_SOURCE_CONFIGURATION_DEVICE_DRIVER_V1
    - WHEA_ERROR_SOURCE_CORRECT_DEVICE_DRIVER
    - WHEA_ERROR_SOURCE_DESCRIPTOR
    - WHEA_ERROR_SOURCE_INITIALIZE_DEVICE_DRIVER
    - WHEA_ERROR_SOURCE_UNINITIALIZE_DEVICE_DRIVER
    - WHEA_GENERIC_ERROR_DESCRIPTOR
    - WHEA_GENERIC_ERROR_DESCRIPTOR_V2
    - WHEA_IPF_CMC_DESCRIPTOR
    - WHEA_IPF_CPE_DESCRIPTOR
    - WHEA_IPF_MCA_DESCRIPTOR
    - WHEA_NOTIFICATION_FLAGS
    - WHEA_NOTIFICATION_DESCRIPTOR
    - WHEA_PCI_SLOT_NUMBER
    - WHEA_XPF_CMC_DESCRIPTOR
    - WHEA_XPF_MCE_DESCRIPTOR
    - WHEA_XPF_MC_BANK_DESCRIPTOR
    - WHEA_XPF_NMI_DESCRIPTOR
    - XPF_MCE_FLAGS
    - XPF_MC_BANK_FLAGS
    - XPF_MC_BANK_FLAGS
    - XSTATE_CONFIG_FEATURE_MSC_INFO
    - CPU_INFORMATION
    - MINIDUMP_SYSTEM_INFO
    - IMAGE_FUNCTION_ENTRY64
    - IMAGE_LOAD_CONFIG_DIRECTORY64
    - IMAGE_OPTIONAL_HEADER64
    - IMAGE_NT_HEADERS64
    - LOADED_IMAGE
    - IPMI_OS_SEL_RECORD
    - MINIDUMP_CALLBACK_INFORMATION
    - MINIDUMP_MODULE_CALLBACK
    - MINIDUMP_CALLBACK_INPUT
    - MINIDUMP_CALLBACK_OUTPUT
    - MINIDUMP_CALLBACK_ROUTINE
    - MINIDUMP_EXCEPTION
    - MINIDUMP_EXCEPTION_INFORMATION
    - MINIDUMP_EXCEPTION_INFORMATION64
    - MINIDUMP_EXCEPTION_STREAM
    - MINIDUMP_FUNCTION_TABLE_DESCRIPTOR
    - MINIDUMP_HANDLE_DESCRIPTOR
    - MINIDUMP_HANDLE_DESCRIPTOR_2
    - MINIDUMP_HEADER
    - MINIDUMP_INCLUDE_MODULE_CALLBACK
    - MINIDUMP_INCLUDE_THREAD_CALLBACK
    - MINIDUMP_IO_CALLBACK
    - MINIDUMP_LOCATION_DESCRIPTOR64
    - MINIDUMP_MEMORY64_LIST
    - MINIDUMP_MEMORY_DESCRIPTOR
    - MINIDUMP_MEMORY_DESCRIPTOR64
    - MINIDUMP_MEMORY_INFO
    - MINIDUMP_MEMORY_INFO_LIST
    - MINIDUMP_MEMORY_INFO_LIST
    - MINIDUMP_MEMORY_LIST
    - MINIDUMP_MISC_INFO_5
    - MINIDUMP_MODULE
    - MINIDUMP_MODULE_CALLBACK
    - MINIDUMP_MODULE_LIST
    - MINIDUMP_PROCESS_VM_COUNTERS_1
    - MINIDUMP_PROCESS_VM_COUNTERS_2
    - MINIDUMP_READ_MEMORY_FAILURE_CALLBACK
    - MINIDUMP_SYSTEM_BASIC_INFORMATION
    - MINIDUMP_SYSTEM_BASIC_PERFORMANCE_INFORMATION
    - MINIDUMP_SYSTEM_FILECACHE_INFORMATION
    - MINIDUMP_SYSTEM_INFO
    - MINIDUMP_SYSTEM_MEMORY_INFO_1
    - MINIDUMP_SYSTEM_PERFORMANCE_INFORMATION
    - MINIDUMP_THREAD
    - MINIDUMP_THREAD_CALLBACK
    - MINIDUMP_THREAD_EX
    - MINIDUMP_THREAD_EX_CALLBACK
    - MINIDUMP_THREAD_EX_LIST
    - MINIDUMP_THREAD_INFO
    - MINIDUMP_THREAD_LIST
    - MINIDUMP_THREAD_NAME
    - MINIDUMP_THREAD_NAME_LIST
    - MINIDUMP_TOKEN_INFO_HEADER
    - MINIDUMP_TOKEN_INFO_LIST
    - MINIDUMP_UNLOADED_MODULE
    - MINIDUMP_UNLOADED_MODULE_LIST
    - MINIDUMP_UNLOADED_MODULE_LIST
    - MINIDUMP_USER_STREAM
    - MINIDUMP_USER_STREAM_INFORMATION
    - MINIDUMP_VM_POST_READ_CALLBACK
    - MINIDUMP_VM_PRE_READ_CALLBACK
    - MINIDUMP_VM_QUERY_CALLBACK

    - IActiveScriptProfilerHeapEnum
    - IActiveScriptProfilerControl3
    - IActiveScriptProfilerControl4
    - IActiveScriptProfilerControl5
    - IDebugApplicationNode100
    - IDebugDataSpaces3
    - IDebugDataSpaces4

    - ExtendedDebugPropertyInfo
    - DebugPropertyInfo
    - DebugHelper
    - DebugStackFrameDescriptor
    - DebugStackFrameDescriptor64
    - DebugPropertyInfo
    - ScriptDebugEventInformation
    - AddVectoredContinueHandler
    - AddVectoredExceptionHandler
    - Beep
    - BindImage
    - BindImageEx
    - CheckRemoteDebuggerPresent
    - CheckSumMappedFile
    - CloseThreadWaitChainSession
    - ContinueDebugEvent
    - CopyContext
    - CreateDataModelManager
    - DbgHelpCreateUserDump
    - DbgHelpCreateUserDumpW
    - DebugActiveProcess
    - DebugActiveProcessStop
    - DebugBreak
    - DebugBreakProcess
    - DebugConnect
    - DebugConnectWide
    - DebugCreate
    - DebugCreateEx
    - DebugSetProcessKillOnExit
    - DecodePointer
    - DecodeRemotePointer
    - DecodeSystemPointer
    - EncodePointer
    - EncodeRemotePointer
    - EncodeSystemPointer
    - EnumDirTree
    - EnumDirTreeW
    - EnumerateLoadedModules
    - EnumerateLoadedModules64
    - EnumerateLoadedModulesEx
    - EnumerateLoadedModulesExW
    - EnumerateLoadedModulesW64
    - FatalAppExitA
    - FatalAppExitW
    - FatalExit
    - FindDebugInfoFile
    - FindDebugInfoFileEx
    - FindDebugInfoFileExW
    - FindExecutableImage
    - FindExecutableImageEx
    - FindExecutableImageExW
    - FindFileInPath
    - FindFileInSearchPath
    - FlushInstructionCache
    - FormatMessageA
    - FormatMessageW
    - GetEnabledXStateFeatures
    - GetErrorMode
    - GetImageConfigInformation
    - GetImageUnusedHeaderBytes
    - GetSymLoadError
    - GetThreadContext
    - GetThreadErrorMode
    - GetThreadSelectorEntry
    - GetThreadWaitChain
    - GetTimestampForLoadedLibrary
    - GetXStateFeaturesMask
    - ImageAddCertificate
    - ImageDirectoryEntryToData
    - ImageDirectoryEntryToDataEx
    - ImageEnumerateCertificates
    - ImageGetCertificateData
    - ImageGetCertificateHeader
    - ImageGetDigestStream
    - ImageLoad
    - ImageNtHeader
    - ImageRemoveCertificate
    - ImageRvaToSection
    - ImageRvaToVa
    - ImageUnload
    - ImagehlpApiVersion
    - ImagehlpApiVersionEx
    - InitializeContext
    - InitializeContext2
    - IsDebuggerPresent
    - LocateXStateFeature
    - MakeSureDirectoryPathExists
    - MapAndLoad
    - MapFileAndCheckSumA
    - MapFileAndCheckSumW
    - MessageBeep
    - MiniDumpReadDumpStream
    - MiniDumpWriteDump
    - OpenThreadWaitChainSession
    - OutputDebugStringA
    - OutputDebugStringW
    - RaiseException
    - RaiseFailFastException
    - RangeMapAddPeImageSections
    - RangeMapCreate
    - RangeMapFree
    - RangeMapRead
    - RangeMapRemove
    - RangeMapWrite
    - ReBaseImage
    - ReBaseImage64
    - ReadProcessMemory
    - RegisterWaitChainCOMCallback
    - RemoveInvalidModuleList
    - RemoveVectoredContinueHandler
    - RemoveVectoredExceptionHandler
    - ReportSymbolLoadSummary
    - RtlAddFunctionTable
    - RtlAddFunctionTable
    - RtlAddGrowableFunctionTable
    - RtlAddGrowableFunctionTable
    - RtlCaptureContext
    - RtlCaptureContext2
    - RtlCaptureStackBackTrace
    - RtlDeleteFunctionTable
    - RtlDeleteFunctionTable
    - RtlDeleteGrowableFunctionTable
    - RtlGrowFunctionTable
    - RtlInstallFunctionTableCallback
    - RtlLookupFunctionEntry
    - RtlLookupFunctionEntry
    - RtlPcToFileHeader
    - RtlRaiseException
    - RtlRestoreContext
    - RtlUnwindEx
    - RtlVirtualUnwind
    - SearchTreeForFile
    - SearchTreeForFileW
    - SetCheckUserInterruptShared
    - SetErrorMode
    - SetImageConfigInformation
    - SetSymLoadError
    - SetThreadContext
    - SetThreadErrorMode
    - SetUnhandledExceptionFilter
    - SetXStateFeaturesMask
    - StackWalk
    - StackWalk64
    - StackWalkEx
    - TerminateProcessOnMemoryExhaustion
    - TouchFileTimes
    - UnDecorateSymbolName
    - UnDecorateSymbolNameW
    - UnMapAndLoad
    - UpdateDebugInfoFile
    - UpdateDebugInfoFileEx
    - WaitForDebugEvent
    - WaitForDebugEventEx
    - Wow64GetThreadContext
    - Wow64GetThreadSelectorEntry
    - Wow64SetThreadContext
    - WriteProcessMemory
  Windows.Win32.System.Environment:
    - ENCLAVE_IDENTITY
    - ENCLAVE_INFORMATION
    - VBS_BASIC_ENCLAVE_BASIC_CALL_GET_ENCLAVE_INFORMATION
    - VBS_ENCLAVE_REPORT
    - VBS_ENCLAVE_REPORT_MODULE
    - VBS_ENCLAVE_REPORT
    - VBS_ENCLAVE_REPORT_PKG_HEADER
    - VBS_ENCLAVE_REPORT_VARDATA_HEADER
    - VBS_BASIC_ENCLAVE_SYSCALL_PAGE

    - EnclaveGetEnclaveInformation
    - EnclaveUnsealData
  Windows.Win32.System.SystemInformation:
    - DnsHostnameToComputerNameExW
    - EnumSystemFirmwareTables
    - GetFirmwareType
    - GetIntegratedDisplaySize
    - IsWow64GuestMachineSupported
    - IsUserCetAvailableInEnvironment
  Windows.Win32.Storage.FileSystem:
    - TXF_ID
    - TXF_LOG_RECORD_AFFECTED_FILE
    - TXF_LOG_RECORD_TRUNCATE
    - TXF_LOG_RECORD_WRITE

    - LockFileEx
    - LockFile
    - BuildIoRingCancelRequest
    - BuildIoRingReadFile
    - TxfLogCreateFileReadContext
    - TxfLogCreateRangeReadContext
    - TxfLogDestroyReadContext
    - TxfLogReadRecords
    - TxfReadMetadataInfo
    - TxfLogRecordGetFileName
    - TxfLogRecordGetGenericType
    - TxfSetThreadMiniVersionForCreate
    - TxfSetThreadMiniVersionForCreate
  Windows.Win32.System.Console:
    - GetConsoleFontSize
    - GetLargestConsoleWindowSize
  Windows.Win32.System.SystemServices:
    - DISPATCHER_CONTEXT_NONVOLREG_ARM64
    - IMAGE_ALPHA64_RUNTIME_FUNCTION_ENTRY
    - IMAGE_AUX_SYMBOL
    - IMAGE_AUX_SYMBOL_EX
    - IMAGE_AUX_SYMBOL_TOKEN_DEF
    - IMAGE_DOS_HEADER
    - IMAGE_DYNAMIC_RELOCATION32
    - IMAGE_DYNAMIC_RELOCATION32_V2
    - IMAGE_DYNAMIC_RELOCATION64
    - IMAGE_DYNAMIC_RELOCATION64_V2
    - IMAGE_EPILOGUE_DYNAMIC_RELOCATION_HEADER
    - IMAGE_IMPORT_CONTROL_TRANSFER_DYNAMIC_RELOCATION
    - IMAGE_IMPORT_DESCRIPTOR
    - IMAGE_INDIR_CONTROL_TRANSFER_DYNAMIC_RELOCATION
    - IMAGE_LINENUMBER
    - IMAGE_OS2_HEADER
    - IMAGE_POLICY_ENTRY
    - IMAGE_POLICY_METADATA
    - IMAGE_RELOCATION
    - IMAGE_RESOURCE_DIRECTORY_ENTRY
    - IMAGE_SWITCHTABLE_BRANCH_DYNAMIC_RELOCATION
    - IMAGE_SYMBOL
    - IMAGE_SYMBOL_EX
    - IMAGE_TLS_DIRECTORY32
    - IMAGE_TLS_DIRECTORY64
    - IMAGE_VXD_HEADER
    - IMPORT_OBJECT_HEADER
    - KERNEL_CET_CONTEXT
    - NON_PAGED_DEBUG_INFO
    - NON_PAGED_DEBUG_INFO
    - NT_TIB32
    - NT_TIB64
  Windows.Win32.Graphics.Gdi:
    - EMRSETMITERLIMIT
    - EMRPOLYTEXTOUTA
    - EMREXTTEXTOUTA
    - EMRANGLEARC
    - ABCFLOAT
    - XFORM
    - EMRTRANSPARENTBLT
    - EMRSTRETCHBLT
    - EMRSETWORLDTRANSFORM
    - EMRPLGBLT
    - EMRMODIFYWORLDTRANSFORM
    - EMRMASKBLT
    - EMRBITBLT
    - EMRALPHABLEND
    - BITMAPFILEHEADER
    - METAHEADER

    - SetWorldTransform
    - ModifyWorldTransform
    - GetWorldTransform
    - GetCharABCWidthsFloatW
    - GetCharABCWidthsFloatA
    - ExtCreateRegion
    - CombineTransform
    - AngleArc
    - SetMiterLimit
  Windows.Win32.Graphics.DirectDraw: []
  Windows.Win32.UI.WindowsAndMessaging:
    - DLGITEMTEMPLATE
    - DLGTEMPLATE

    - CreateDialogIndirectParamA
    - CreateDialogIndirectParamW
    - DialogBoxIndirectParamA
    - DialogBoxIndirectParamW

exclude_libraries:
  - icu
  - clfsw32
  - dbghelp
  - mrmsupport
  - dciman32

unwindable_functions:
  - ExitThread
  - ExitProcess

callbacking_functions:
  - CreateWindowExA
  - DispatchMessageA

com_classes:
  Windows.Win32.Graphics.DirectDraw:
    - name: DirectDraw
      interfaces:
        - Windows.Win32.Graphics.DirectDraw.IDirectDraw
    - name: DirectDrawSurface
      interfaces:
        - Windows.Win32.Graphics.DirectDraw.IDirectDrawSurface
