
[package]
name = "win32"
version = "0.0.1"
edition = "2018"

[dependencies]
core-mem = { path = "../core-mem" }
core-abi = { path = "../core-abi" }
core-str = { path = "../core-str" }

anymap = "0.12.1"
downcast-rs = "1.2.0"
