[package]
name = "core-abi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_assertions = "1.1.0"
core-mem = { path = "../core-mem" }
rusty-x86 = { path = "../rusty-x86", optional = true }