[package]
name = "rusty-x86_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.36"
proc-macro-crate = "1.1.0"
quote = "1.0.15"
syn = "1.0.86"
hex = "0.4.3"

[lib]
proc-macro = true
